import { mkdir, open, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Readable } from "node:stream";

/**
 * Where uploaded bytes live. Keys are generated by the app (never client
 * input), so implementations can map them straight to paths or object names.
 * Swap LocalFileStorage for an S3/GCS implementation when running more than
 * one instance.
 */
export interface FileStorage {
  save(key: string, data: Buffer): Promise<void>;
  /** Opens the file; rejects (e.g. ENOENT) before any byte is streamed. */
  read(key: string): Promise<Readable>;
  /** Removes the file; a missing file is not an error. */
  delete(key: string): Promise<void>;
}

const SAFE_KEY = /^[A-Za-z0-9-]{1,64}$/;

/**
 * Stores files in a local directory.
 */
export class LocalFileStorage implements FileStorage {
  private readonly root: string;

  constructor(directory: string) {
    this.root = path.resolve(directory);
  }

  async save(key: string, data: Buffer): Promise<void> {
    await mkdir(this.root, { recursive: true });
    // "wx" fails instead of overwriting if the key is ever reused.
    await writeFile(this.pathOf(key), data, { flag: "wx" });
  }

  async read(key: string): Promise<Readable> {
    const handle = await open(this.pathOf(key), "r");
    return handle.createReadStream();
  }

  async delete(key: string): Promise<void> {
    await rm(this.pathOf(key), { force: true });
  }

  /** Defence in depth: keys are generated, but never let one escape root. */
  private pathOf(key: string) {
    if (!SAFE_KEY.test(key)) {
      throw new Error(`Invalid storage key: ${key}`);
    }

    return path.join(this.root, key);
  }
}
