import { randomUUID } from "node:crypto";
import {
  bigint,
  datetime,
  index,
  json,
  mysqlEnum,
  mysqlTable,
  varchar,
} from "drizzle-orm/mysql-core";

import { USER_ROLES } from "../modules/users/user.entity";

/** UUID primary key generated by the app, so inserts know the id up front. */
const id = () =>
  varchar("id", { length: 36 })
    .primaryKey()
    .$defaultFn(() => randomUUID());

/** Millisecond-precision DATETIME read as a JS Date (stored in UTC). */
const timestamp = (name: string) => datetime(name, { mode: "date", fsp: 3 });

const timestamps = {
  createdAt: timestamp("created_at")
    .notNull()
    .$defaultFn(() => new Date()),
  updatedAt: timestamp("updated_at")
    .notNull()
    .$defaultFn(() => new Date())
    .$onUpdateFn(() => new Date()),
};

/**
 * Deleted users keep their row (`deletedAt` set), so audit history and
 * foreign keys stay intact. Their email stays reserved.
 */
export const users = mysqlTable(
  "users",
  {
    id: id(),
    name: varchar("name", { length: 100 }).notNull(),
    email: varchar("email", { length: 255 }).notNull().unique(),
    passwordHash: varchar("password_hash", { length: 255 }).notNull(),
    role: mysqlEnum("role", USER_ROLES).notNull().default("user"),
    ...timestamps,
    deletedAt: timestamp("deleted_at"),
  },
  (table) => [index("users_created_at_idx").on(table.createdAt)],
);

/**
 * Refresh tokens are stored as SHA-256 hashes, never in plain text. Tokens
 * issued from the same login share a `familyId`, so a reused (stolen) token
 * can revoke the whole session.
 */
export const refreshTokens = mysqlTable(
  "refresh_tokens",
  {
    id: id(),
    userId: varchar("user_id", { length: 36 })
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    tokenHash: varchar("token_hash", { length: 64 }).notNull().unique(),
    familyId: varchar("family_id", { length: 36 }).notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    revokedAt: timestamp("revoked_at"),
    createdAt: timestamps.createdAt,
  },
  (table) => [
    index("refresh_tokens_user_id_idx").on(table.userId),
    index("refresh_tokens_family_id_idx").on(table.familyId),
  ],
);

/**
 * Append-only record of security-relevant actions. `actorId` is null for
 * actions without a signed-in user (CLI, system). No foreign keys, so the
 * history survives whatever happens to the rows it mentions.
 */
export const auditLogs = mysqlTable(
  "audit_logs",
  {
    id: id(),
    actorId: varchar("actor_id", { length: 36 }),
    action: varchar("action", { length: 64 }).notNull(),
    entityType: varchar("entity_type", { length: 64 }).notNull(),
    entityId: varchar("entity_id", { length: 36 }),
    metadata: json("metadata").$type<Record<string, unknown>>(),
    ip: varchar("ip", { length: 45 }),
    requestId: varchar("request_id", { length: 128 }),
    createdAt: timestamps.createdAt,
  },
  (table) => [
    index("audit_logs_actor_id_idx").on(table.actorId),
    index("audit_logs_entity_idx").on(table.entityType, table.entityId),
    index("audit_logs_created_at_idx").on(table.createdAt),
  ],
);

/**
 * Metadata of uploaded files. The bytes live in the file storage under
 * `storageKey`, a generated name that never contains client input.
 */
export const files = mysqlTable(
  "files",
  {
    id: id(),
    ownerId: varchar("owner_id", { length: 36 })
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    originalName: varchar("original_name", { length: 255 }).notNull(),
    mimeType: varchar("mime_type", { length: 100 }).notNull(),
    size: bigint("size", { mode: "number", unsigned: true }).notNull(),
    storageKey: varchar("storage_key", { length: 64 }).notNull().unique(),
    createdAt: timestamps.createdAt,
  },
  (table) => [index("files_owner_id_idx").on(table.ownerId)],
);
